### ISSUE TITLE
example

### ISSUE THREAD

**Issue by jaygambetta** [QISKit/qiskit-addon-sympy#11]
the example should not have shots as an option and we should use get_statevector and get_unitary

**Comment by yaelbh** [comment]
It should indeed not have shots, and I will remove them. Behind the scenes this is what will happen:
- Execute will assign a default number of 1024 shots.
- The statevector simulator will set the number of shots to 1, while sending a logger.info message "statevector simulator only supports 1 shot. Setting shots=1".

In the future, we should consider changing execute, such that it will not assign a default number of shots to statevector simulators. This will allow us, from within the statevector simulator, to display a logger.warning if the number of shots is explicitly given and different from 1.
