### ISSUE TITLE
Repository conventions and meta-documentation

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-addon-sympy#17]
As hinted in https://github.com/QISKit/qiskit-addon-projectq/pull/3, it is a bit unclear at the moment how to collaborate in this repository (and in `qiskit-addon-projectq`). A proposal would be to try to make things as closer to `qiskit-core` as possible (working via pull request, reviewers, etc), which in practice would involve bringing a number of files to this repo (issue templates, codeowners, docs, etc) with some tuning as needed.

@jaygambetta @ajavadia do you have any preferences about the workflow for these two repositories?

**Comment by jaygambetta** [comment]
I dont have a preference for them as we should allow the owner of addons to decide.

**Comment by diego-plan9** [comment]
Sounds good to me! @yaelbh , @yehuda-naveh , is there any organizational feature (github settings for branches, etc) or similar (issue templates, collaboration documents, etc) from the main repository that you would like to include and that I can help with?

**Comment by yaelbh** [comment]
@diego-plan9 I think it's currently OK, I guess that we will discover these in time. @yehuda-naveh would you like any of these features?

**Comment by yehuda-naveh** [comment]
I'm ok as well for now, thanks

**Comment by diego-plan9** [comment]
Closing the issue then, for tidying up the repo! If there is anything from terra in the "meta" department that we can help with, please feel free to ping :+1:
