### ISSUE TITLE
Remove Shots

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-addon-sympy#22]
I want to remove the concept of shots all together from a state-vector. We should think about how we do this.

**Comment by yaelbh** [comment]
Please see a proposal for a refactoring here: https://github.com/QISKit/qiskit-core/pull/436#issuecomment-394252410
In short, it suggests to maintain separate classes for qasm and statevector simulators, so the notion of shots will not exist for the statevector simulators.

**Comment by jaygambetta** [comment]
sure but in sympy there is no qasm so i think we can just remove shots now from it

**Comment by yaelbh** [comment]
Right, so I'll remove set_shots_to_1 from statevector_simulator_sympy

**Comment by yaelbh** [comment]
Waiting for the open pull requests to be merged. It is currently difficult to work with this code because it is not synchronized with recent qiskit updates.
