### ISSUE TITLE
Launch a new repository qiskit-addon-sympy

### ISSUE THREAD

**Issue by yaelbh** [QISKit/qiskit-addon-sympy#3]
This module is currently still in Test PyPI. It can be installed like this:
pip install --index-url https://test.pypi.org/simple qiskit_addon_sympy --extra-index-url https://pypi.org/simple

@ajavadia @chriseclectic @jaygambetta Could you please review. We will be able to move to PyPI when approved.

**Comment by yaelbh** [comment]
Following https://github.com/QISKit/qiskit-core/commit/6bbc764534dab1c164fc73c8d825d7fb69cd5d19, I will update the license here as well.

**Comment by diego-plan9** [comment]
> Following QISKit/qiskit-core@6bbc764, I will update the license here as well.

Great - I opened #5 before realizing you were already on it :tada:

**Comment by jaygambetta** [comment]
I think we can close this
