### ISSUE TITLE
Tests improvements: make them runnable, style

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-addon-sympy#4]
It seems that currently the tests are not runnable as standalone, as they require `from test.python.common import QiskitTestCase`:

```
======================================================================
ERROR: test_statevector_simulator_sympy (unittest.loader._FailedTest)
----------------------------------------------------------------------
...
    from test.python.common import QiskitTestCase
ImportError: No module named 'test.python'
```

Would it be possible to add a `test/common.py` file with a trimmed down version of the equivalent file from core? The current one in `qiskit-core` contains functionality that is not really needed for this repository, and it would just make things less complex - probably would be enough with just (I have not tested it!):

```
from qiskit-addon-sympy import __path__ as main_path

class Path(Enum):
    """Helper with paths commonly used during the tests."""
    # Main qiskit-addon-sympy path:    qiskit-addon-sympy/
    SDK = main_path[0]
    # test.python path: qiskit-addon-sympy/test/
    TEST = os.path.dirname(__file__)
    # Examples path:    examples/
    EXAMPLES = os.path.join(SDK, '../examples')


class QiskitTestCase(unittest.TestCase):
    """Helper class that contains common functionality."""

    @classmethod
    def setUpClass(cls):
        cls.moduleName = os.path.splitext(inspect.getfile(cls))[0]
        cls.log = logging.getLogger(cls.__name__)

        # Set logging to file and stdout if the LOG_LEVEL environment variable
        # is set.
        if os.getenv('LOG_LEVEL'):
            # Set up formatter.
            log_fmt = ('{}.%(funcName)s:%(levelname)s:%(asctime)s:'
                       ' %(message)s'.format(cls.__name__))
            formatter = logging.Formatter(log_fmt)

            # Set up the file handler.
            log_file_name = '%s.log' % cls.moduleName
            file_handler = logging.FileHandler(log_file_name)
            file_handler.setFormatter(formatter)
            cls.log.addHandler(file_handler)

            # Set the logging level from the environment variable, defaulting
            # to INFO if it is not a valid level.
            level = logging._nameToLevel.get(os.getenv('LOG_LEVEL'),
                                             logging.INFO)
            cls.log.setLevel(level)

    @staticmethod
    def _get_resource_path(filename, path=Path.TEST):
        """ Get the absolute path to a resource.

        Args:
            filename (string): filename or relative path to the resource.
            path (Path): path used as relative to the filename.
        Returns:
            str: the absolute path to the resource.
        """
        return os.path.normpath(os.path.join(path.value, filename))
```

**Comment by diego-plan9** [comment]
Additionally, can we:
- rename the `test_sympy/` folder to just `test`? This would make it a bit closer to the name the testing tools expect, and actually allow the `Makefile` to just do a `python3 -m unittest discover -v`
- revise the tests so they do not use `QuantumProgram`? There is a `qiskit.load_qasm_file()` function now that should do the trick.

**Comment by yehuda-naveh** [comment]
Hi @diego-plan9 , not-runnable tests as standalones was a design decision. The issue is that if you just pip-install Qiskit, you don't have access to the Qiskit tests, so you need to do a full clone. The other option you suggest is to actually do a full copy of the tests (entire code duplication of the test libraries between all add-ons). We decided not to go this way mainly because of the maintenance nightmare - there's no chance that anyone doing a fix or enhancement to a Qiskit test will remember to do it also in all the duplicated code in the add-ons. What's more, once each add-on test is evolved separately, duplicating the change may be not trivial even if we remember to do it). So we preferred to pay by having anyone who needs to test the add-on code (presumably a developer) - to need to clone qiskit. They'd probably have qiskit cloned anyway, and even if not, it's a small price compared to the maintenance issue. What do you think?

**Comment by diego-plan9** [comment]
Thanks for sharing the rationale, @yehuda-naveh ! Avoiding duplication of the entire test suite (and indeed the maintenance troubles it would involve in the future to keep everything in sync and allow growing each addon independently) is a more than valid concern, and definitively not the route we want to take.

However, in this case, what I'm suggesting is only porting the minimal amount of code needed (ie. a very trimmed down `test/_common.py`) - could you let me know which other tests from `qiskit-core` you think would be beneficial to include in this repository? As things stand, I believe the main `qiskit-core` test suite would not use this simulator in most (if not all) cases, which would make including all the test suite (or cloning the repository only for that purpose) a bit overkill.

But I think the main concern is isolation: ideally, if an addon depends on `qiskit-core` (the pip installable package), in principle it should only assume that it can use what is provided by `pip install qiskit-core`. Conceptually, the tests for the addon should assume that the core is properly tested, and only include the ones relevant to the custom functionality of the backend - this reduces the complexity and makes the dependency only on the deliverables (ie the package), not the repository, which has a number of practical benefits as well (in particular, requiring cloning is problematic). There is indeed a grey area of sorts: for example, for the backend addons, there will most likely be a number of similar tests for them (such as creating the instance, getting it through the provider, etc) - I would actually like to include a generic form of those tests as part of the `qiskit-core` pip package (so addons can do something like `from qiskit.test import BackendTest` and benefit from a "standard test suite only for backends), but we are not there yet.

So what about:
* proceed with including the minimal version of `test/_common.py` on this repo, adjusting the existing tests as needed
* create a new `test/test_backend.py` that is generic and does not contain a reference to any specific backend (but does contain tests about instantiation and running a circuit), but instead is meant to be subclassed by each backend addon. This file would eventually be moved to `qiskit-core` once.

**Comment by diego-plan9** [comment]
> As for renaming test_sympy to 'test' created collision issues with Qiskit. This is a smaller issue than the not-runable tests, maybe we can patch it somehow to work if it's important

Forgot to comment on it! The name of the folder is not really that important, but following the isolation idea mentioned above, we should not be constrained by the structure of `qiskit-core` repo when deciding the names on this project :)

**Comment by yaelbh** [comment]
Thanks @diego-plan9 for the detailed answer. test.python._random_circuit_generator is imported in the ProjectQ test. Do you suggest to duplicate it as well, as a temporary solution, until "test" becomes part of qiskit-core pip package?

**Comment by diego-plan9** [comment]
> Thanks @diego-plan9 for the detailed answer. test.python._random_circuit_generator is imported in the ProjectQ test. Do you suggest to duplicate it as well, as a temporary solution, until "test" becomes part of qiskit-core pip package?

Yes, please do! Can you also open an issue on that repository, keeping track of the files that have been copied from `core`, so we can find them easily later?

> I like very much your vision of having all generic tests and code running them in the core pip-install base. This would solve the problem and I think it is good design in this case. So if you are willing to go ahead with this and give us a green line - I think we can implement this relatively shortly (again, @yaelbh correct me if I'm wrong). It would mean a generic simulator-test lib with API's to specific tests at the qiskit main code base

@yehuda-naveh : yes, please, go ahead! It sounds like a good compromise for the time being, and hopefully the amounts of files to be "temporarily copied" until we have full support in the pip package will be manageable.

**Comment by yaelbh** [comment]
@diego-plan9 @yehuda-naveh Following the above discussion, there will be three pull requests:

- [ ] Pull request (A) .
  - [ ] Rename test_sympy to test.
  - [ ] Copy and adjust _common.py.
  - [ ] Write test_backend.py (which includes definition of class BackendTest) and use it in Sympy tests.
  - [ ] Maintain a list of files that were copied from qiskit-core.
  - [ ] At this point Sympy tests run smoothly with pip installed QISKit.
- [ ] Pull request (B).
  - [ ] Replace the usage of QuantumProgram with load_qasm_file. Probably also in qiskit-core.
- [ ] Pull Request (C).
  - [ ] Move files to qiskit-core.
  - [ ] Make qiskit-core tests inherit from BackendTest.

Note:
- Pull requests (A)  and (B) are independent.
- These action items are equally relevant to ProjectQ.
